name: Rust

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Codeball AI Actions
      uses: sturdy-dev/codeball-action@v1.2.0
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MANGO_API_KEY: ${{ secrets.MANGO_API_KEY }}
      MANGO_CLIENT_ID: ${{ secrets.MANGO_CLIENT_ID }}
